From python:3.8.0

ENV PYTHONUNBUFFERED 1

RUN mkdir /stocks
COPY . /stocks
WORKDIR /stocks
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
